version: "3.8"
services:
   db:
    container_name: '${PROJECT_NAME}-mariadb'
    image: mariadb:10.6
    restart: 'always'
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - ./.docker/mariadb/symfony.cnf:/etc/mysql/conf.d/symfony.cnf
      - ./.docker/mariadb/init:/docker-entrypoint-initdb.d
      - dbfiles:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'


   phpserver:
    container_name: '${PROJECT_NAME}-phpserver'
    build:
      context: ./.docker/phpserver
    ports:
      - '9000:9000'
    volumes:
      - ./symfony-app:/var/www/symfony_docker
    depends_on:
      - db
    links:
      - db
      - mailhog

   nginx:
    container_name: '${PROJECT_NAME}-nginx'
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./symfony-app:/var/www/symfony_docker
      - ./.docker/phpserver/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpserver
      - db

   pma:
    container_name: ${PROJECT_NAME}-pma
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_POST_MAX_SIZE: 1G
      UPLOAD_SIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    links:
      - db


   mailhog:
    container_name: '${PROJECT_NAME}-mailhog'
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # MailHog web UI port
volumes:
    dbfiles:
